package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
)

// Isolation outcomes reported back on /complete (Session.isolationStatus): the session
// ran in its own git worktree, or fell back to the shared workDir because it wasn't a
// git repo (the case the UI nudges the user to fix with `git init`). isoShared (no branch
// at all) is internal and not reported.
const (
	isoWorktree    = "worktree"
	isoSharedNoGit = "shared-nogit"
	isoShared      = "shared"
)

// Worktree is a per-session git worktree the runner created for isolation. It lets
// concurrent sessions on the same agent edit files without clobbering each other: each
// runs claude in its own checkout on its own branch, forked from the workDir HEAD at
// claim. On terminal completion the runner commits the work to Branch and removes the
// checkout — the branch stays behind for a manual merge in the UI.
type Worktree struct {
	Path    string // the worktree checkout dir
	Branch  string // orbit/<slug>-<hash>
	BaseSha string // commit Branch forked from (workDir HEAD at claim)
	RepoDir string // the git repo root, for `git -C RepoDir worktree ...`
	Session string // session id (names the checkout dir + base ref)
}

// git runs `git -C dir <args...>` and returns trimmed stdout. On a non-zero exit the
// returned error is an *exec.ExitError whose .Stderr carries git's message.
func git(dir string, args ...string) (string, error) {
	out, err := exec.Command("git", append([]string{"-C", dir}, args...)...).Output()
	return strings.TrimSpace(string(out)), err
}

// isGitRepo reports whether dir is inside a git work tree.
func isGitRepo(dir string) bool {
	out, err := git(dir, "rev-parse", "--is-inside-work-tree")
	return err == nil && out == "true"
}

func branchExists(repoRoot, branch string) bool {
	_, err := git(repoRoot, "rev-parse", "--verify", "--quiet", "refs/heads/"+branch)
	return err == nil
}

// defaultGitignore is written into a non-git workDir before its baseline commit (only when
// the dir has no .gitignore of its own), so auto-init doesn't sweep dependencies, build
// output, or secrets into version control.
const defaultGitignore = `# Auto-generated by Orbit when enabling worktree isolation.
node_modules/
dist/
build/
out/
.next/
.turbo/
target/
__pycache__/
*.pyc
.venv/
venv/
.env
.env.*
*.log
.DS_Store
.idea/
.vscode/
`

// initGitRepo turns a non-git workDir into a git repo so its sessions can be isolated:
// writes a conservative .gitignore (only if absent), `git init`, stages everything, and
// makes a baseline commit. Triggered only when the agent opted in (autoInitGit). Returns an
// error if the repo isn't usable afterward — no baseline commit means no HEAD to fork from.
func initGitRepo(dir string) error {
	if _, err := os.Stat(filepath.Join(dir, ".gitignore")); os.IsNotExist(err) {
		_ = os.WriteFile(filepath.Join(dir, ".gitignore"), []byte(defaultGitignore), 0o644)
	}
	if _, err := git(dir, "init"); err != nil {
		return err
	}
	if _, err := git(dir, "add", "-A"); err != nil {
		return err
	}
	// Inline identity + --no-verify so the baseline never fails on a runner with no git
	// user.* set or a stray hook; --allow-empty so even an empty dir gets a HEAD to fork.
	_, err := git(dir,
		"-c", "user.email=runner@orbit", "-c", "user.name=Orbit Runner",
		"commit", "--no-verify", "--allow-empty", "-m", "orbit: baseline")
	return err
}

// worktreesDir holds per-session checkouts, outside any repo so they're easy to GC and
// never nest inside an agent's tree. Sibling of the runner's scratch `runs` dir.
func worktreesDir() string {
	d := filepath.Join(machineHome(), "worktrees")
	_ = os.MkdirAll(d, 0o755)
	return d
}

func baseRefName(sessionID string) string { return "refs/orbit-base/" + sessionID }

func shortSha(sha string) string {
	if len(sha) > 8 {
		return sha[:8]
	}
	return sha
}

// setupWorktree ensures a per-session git worktree exists for job and returns the dir
// claude should run in. When job has no branch, baseDir isn't a git repo, or the repo has
// no commits, it returns baseDir unchanged (shared-dir fallback) and records why on
// job.IsolationStatus. Otherwise it sets job.WT and returns the checkout's exec dir.
func setupWorktree(job *ClaimedSession, baseDir string) string {
	if job.Branch == "" {
		job.IsolationStatus = isoShared
		return baseDir
	}
	if !isGitRepo(baseDir) {
		// Not a git repo. If the agent opted in (autoInitGit, set by the web "Enable
		// isolation" action), initialize one so the session can still be isolated;
		// otherwise run shared and nudge the user via isolationStatus=shared-nogit.
		if !job.AutoInitGit {
			job.IsolationStatus = isoSharedNoGit
			logln(fmt.Sprintf("session %s — workDir %q is not a git repo; running shared (no isolation)", job.SessionID, baseDir))
			return baseDir
		}
		if err := initGitRepo(baseDir); err != nil {
			job.IsolationStatus = isoSharedNoGit
			logln(fmt.Sprintf("session %s — auto git init of %q failed (%v); running shared", job.SessionID, baseDir, err))
			return baseDir
		}
		logln(fmt.Sprintf("session %s — auto-initialized git repo at %q (autoInitGit)", job.SessionID, baseDir))
		// Fall through: baseDir is now a git repo with a baseline commit.
	}
	repoRoot, err := git(baseDir, "rev-parse", "--show-toplevel")
	if err != nil || repoRoot == "" {
		job.IsolationStatus = isoSharedNoGit
		return baseDir
	}
	wtPath := filepath.Join(worktreesDir(), job.SessionID)
	// Land claude at the same spot inside the checkout that baseDir is inside the repo,
	// so a workDir that is a subdir of the repo still resolves correctly.
	rel, _ := filepath.Rel(repoRoot, baseDir)
	if rel == "" || rel == "." || strings.HasPrefix(rel, "..") {
		rel = "."
	}
	execDir := filepath.Join(wtPath, rel)

	// Reuse an existing checkout (reclaim/resume after a restart): the dir survives with
	// any uncommitted in-flight work intact. Recover BaseSha from the persisted base ref.
	if isGitRepo(wtPath) {
		base, _ := git(repoRoot, "rev-parse", baseRefName(job.SessionID))
		job.WT = &Worktree{Path: wtPath, Branch: job.Branch, BaseSha: base, RepoDir: repoRoot, Session: job.SessionID}
		job.IsolationStatus = isoWorktree
		logln(fmt.Sprintf("session %s — re-attached worktree %s (branch %s)", job.SessionID, wtPath, job.Branch))
		return execDir
	}

	base, err := git(baseDir, "rev-parse", "HEAD")
	if err != nil || base == "" {
		// An empty repo (no commits) has no HEAD to fork from — run shared instead.
		job.IsolationStatus = isoSharedNoGit
		logln(fmt.Sprintf("session %s — repo has no HEAD; running shared (no isolation)", job.SessionID))
		return baseDir
	}
	// Record the fork point as a ref so it survives a runner restart (the in-memory
	// BaseSha would be lost on reclaim), then create the worktree on the session's branch.
	_, _ = git(repoRoot, "update-ref", baseRefName(job.SessionID), base)
	if branchExists(repoRoot, job.Branch) {
		_, err = git(repoRoot, "worktree", "add", wtPath, job.Branch)
	} else {
		_, err = git(repoRoot, "worktree", "add", "-b", job.Branch, wtPath, base)
	}
	if err != nil {
		_, _ = git(repoRoot, "update-ref", "-d", baseRefName(job.SessionID))
		job.IsolationStatus = isoSharedNoGit
		logln(fmt.Sprintf("session %s — `git worktree add` failed (%v); running shared", job.SessionID, err))
		return baseDir
	}
	job.WT = &Worktree{Path: wtPath, Branch: job.Branch, BaseSha: base, RepoDir: repoRoot, Session: job.SessionID}
	job.IsolationStatus = isoWorktree
	logln(fmt.Sprintf("session %s — isolated in worktree %s (branch %s @ %s)", job.SessionID, wtPath, job.Branch, shortSha(base)))
	return execDir
}

// finalizeWorktree commits whatever the session changed onto its branch and returns the
// per-file diff vs the base. Called once at terminal completion, before /complete, so the
// work is captured on the branch even though the checkout dir may then be removed.
func finalizeWorktree(wt *Worktree, title string) []ChangedFile {
	if _, err := git(wt.Path, "add", "-A"); err != nil {
		logln("worktree add failed for", wt.Session+":", err)
	}
	// `diff --cached --quiet` exits non-zero when something is staged → there's work to commit.
	if _, err := git(wt.Path, "diff", "--cached", "--quiet"); err != nil {
		msg := strings.TrimSpace(title)
		if msg == "" {
			msg = "orbit session " + wt.Session
		}
		// Inline identity so the commit never fails on a runner with no git user.* set;
		// --no-verify so a repo's pre-commit hook can't block finalization.
		if _, err := git(wt.Path,
			"-c", "user.email=runner@orbit", "-c", "user.name=Orbit Runner",
			"commit", "--no-verify", "-m", msg); err != nil {
			logln("worktree commit failed for", wt.Session+":", err)
		}
	}
	if wt.BaseSha == "" {
		return nil
	}
	return diffFiles(wt.Path, wt.BaseSha, "HEAD")
}

// gitEnv runs `git -C dir <args...>` with extra environment (e.g. GIT_INDEX_FILE).
func gitEnv(dir string, env []string, args ...string) (string, error) {
	cmd := exec.Command("git", append([]string{"-C", dir}, args...)...)
	cmd.Env = env
	out, err := cmd.Output()
	return strings.TrimSpace(string(out)), err
}

// diffFiles returns the per-file change summary for the committed `git diff base..head`.
func diffFiles(dir, base, head string) []ChangedFile {
	rng := base + ".." + head
	numOut, err := git(dir, "diff", "--numstat", rng)
	if err != nil {
		logln("worktree diff failed in", dir+":", err)
		return nil
	}
	statusOut, _ := git(dir, "diff", "--name-status", rng)
	return parseNumstat(numOut, statusOut)
}

// liveDiffStat returns the per-file diff of the worktree's CURRENT state (uncommitted +
// untracked) vs its base, for the live status bar while a session is still running. It
// stages into a throwaway temp index (GIT_INDEX_FILE) so it never touches the real index
// claude may be using, and respects .gitignore so node_modules/build output don't show.
func liveDiffStat(wt *Worktree) []ChangedFile {
	if wt == nil || wt.BaseSha == "" {
		return nil
	}
	tmp, err := os.CreateTemp("", "orbit-idx-*")
	if err != nil {
		return nil
	}
	idx := tmp.Name()
	_ = tmp.Close()
	// Remove the empty file first: git rejects a 0-byte index ("index file smaller than
	// expected") — it creates a fresh index at this path instead.
	_ = os.Remove(idx)
	defer os.Remove(idx)
	env := append(os.Environ(), "GIT_INDEX_FILE="+idx)
	if _, err := gitEnv(wt.Path, env, "add", "-A"); err != nil {
		return nil
	}
	numOut, err := gitEnv(wt.Path, env, "diff", "--cached", "--numstat", wt.BaseSha)
	if err != nil {
		return nil
	}
	statusOut, _ := gitEnv(wt.Path, env, "diff", "--cached", "--name-status", wt.BaseSha)
	return parseNumstat(numOut, statusOut)
}

// worktreeIsDirty reports whether the worktree has uncommitted changes right now — tracked
// or untracked, respecting .gitignore (`git status --porcelain` non-empty). Drives the
// status bar's Commit-vs-Merge action. False for a nil/missing worktree.
func worktreeIsDirty(wt *Worktree) bool {
	if wt == nil {
		return false
	}
	out, err := git(wt.Path, "status", "--porcelain")
	return err == nil && out != ""
}

// parseNumstat zips `git diff --numstat` (+/-/path) with `git diff --name-status` (the
// status letter, keyed by the new path for renames) into ChangedFile rows.
func parseNumstat(numOut, statusOut string) []ChangedFile {
	statusBy := map[string]string{}
	for _, line := range strings.Split(statusOut, "\n") {
		f := strings.Fields(line)
		if len(f) >= 2 && len(f[0]) > 0 {
			statusBy[f[len(f)-1]] = string(f[0][0])
		}
	}
	var out []ChangedFile
	for _, line := range strings.Split(numOut, "\n") {
		parts := strings.SplitN(line, "\t", 3)
		if len(parts) != 3 || parts[2] == "" {
			continue
		}
		st := statusBy[parts[2]]
		if st == "" {
			st = "M"
		}
		out = append(out, ChangedFile{
			Path:      parts[2],
			Additions: parseStatInt(parts[0]),
			Deletions: parseStatInt(parts[1]),
			Status:    st,
		})
	}
	return out
}

// parseStatInt parses a numstat count; "-" marks a binary file → -1.
func parseStatInt(s string) int {
	if s == "-" {
		return -1
	}
	n, _ := strconv.Atoi(s)
	return n
}

// removeWorktree tears down the session's checkout (the branch is kept) and drops the base
// ref. For a finished SUCCEEDED/FAILED session; a cancelled session keeps its checkout for
// a possible resume and is reaped by gcWorktrees instead.
func removeWorktree(wt *Worktree) {
	if _, err := git(wt.RepoDir, "worktree", "remove", "--force", wt.Path); err != nil {
		logln("worktree remove failed for", wt.Session+":", err)
		_ = os.RemoveAll(wt.Path)
		_, _ = git(wt.RepoDir, "worktree", "prune")
	}
	_, _ = git(wt.RepoDir, "update-ref", "-d", baseRefName(wt.Session))
}

// mergeLock serializes merges so two "merge to main" requests can't race on the same repo's
// working tree / main ref.
var mergeLock sync.Mutex

// mergeOutcome is what mergeToMain reports: "merged" advanced main (MergedSha = new HEAD),
// "conflict" means the merge was aborted cleanly, "error" means a precondition failed.
// Message carries git's output / the failed precondition for the UI.
type mergeOutcome struct {
	Status    string
	MergedSha string
	Message   string
}

// mergeToMain merges a session's branch into the repo's main on the runner's local repo.
// Conservative by design: it only auto-merges when the repo root is already on a CLEAN main
// (the normal state — isolated sessions run in their own worktrees, so the primary checkout
// sits on main between runs). Any other state returns an "error" outcome with an actionable
// message; the UI keeps a copyable `git merge` fallback for those cases. The session branch
// is never deleted. Serialized by mergeLock so concurrent merges don't race on the repo.
func mergeToMain(req MergeCommand) mergeOutcome {
	mergeLock.Lock()
	defer mergeLock.Unlock()

	repoRoot, err := git(expandTilde(req.WorkDir), "rev-parse", "--show-toplevel")
	if err != nil || repoRoot == "" {
		return mergeOutcome{Status: "error", Message: "workDir is not a git repository"}
	}
	// Detect the merge target: main, else master.
	target := ""
	for _, b := range []string{"main", "master"} {
		if branchExists(repoRoot, b) {
			target = b
			break
		}
	}
	if target == "" {
		return mergeOutcome{Status: "error", Message: "no main or master branch in this repo"}
	}
	if !branchExists(repoRoot, req.Branch) {
		return mergeOutcome{Status: "error", Message: fmt.Sprintf("branch %q not found", req.Branch)}
	}
	// Guard: only merge when the primary checkout is on a clean target branch, so we never
	// disturb an in-progress checkout or leave a half-applied merge in the shared tree.
	if cur, _ := git(repoRoot, "rev-parse", "--abbrev-ref", "HEAD"); cur != target {
		return mergeOutcome{Status: "error", Message: fmt.Sprintf("repo is on %q, not %q — switch to %s and merge manually", cur, target, target)}
	}
	// Block on modified tracked files (a merge would mix them in / could clobber); untracked
	// files are fine — git itself refuses only if the merge would overwrite one, which the
	// error path below catches.
	if st, _ := git(repoRoot, "status", "--porcelain", "--untracked-files=no"); st != "" {
		return mergeOutcome{Status: "error", Message: fmt.Sprintf("%s has uncommitted changes — commit/stash, or merge manually", target)}
	}
	// Inline identity so a merge commit never fails on a runner with no git user.* set.
	out, err := git(repoRoot,
		"-c", "user.email=runner@orbit", "-c", "user.name=Orbit Runner",
		"merge", "--no-edit", req.Branch)
	if err != nil {
		// A failed merge (almost always a conflict, given the clean-tree pre-check). git
		// writes "CONFLICT ..." to stdout (returned as `out`); ExitError carries stderr.
		msg := strings.TrimSpace(out + "\n" + gitStderr(err))
		_, _ = git(repoRoot, "merge", "--abort") // leave the working tree clean
		return mergeOutcome{Status: "conflict", Message: clip(msg, 1000)}
	}
	sha, _ := git(repoRoot, "rev-parse", "HEAD")
	logln(fmt.Sprintf("merged %s into %s (%s) for session %s", req.Branch, target, shortSha(sha), req.SessionID))
	return mergeOutcome{Status: "merged", MergedSha: sha}
}

// commitOutcome is what commitWorktree reports: "committed" advanced the branch, "nochange"
// means the tree was already clean, "error" means a precondition failed / git errored.
type commitOutcome struct {
	Status  string
	Message string
}

// commitWorktree commits a live session's uncommitted worktree changes onto its branch, so
// the user can checkpoint (and then merge) without ending the session. It operates on the
// session's own checkout (worktreesDir()/SessionID), which is separate from the primary repo
// on main, so it never disturbs main or another session. Returns "nochange" when the tree is
// already clean, "committed" on a new commit, "error" if the checkout is missing or git
// fails. Serialized per session by the runloop's in-flight guard.
func commitWorktree(req CommitCommand) commitOutcome {
	wtPath := filepath.Join(worktreesDir(), req.SessionID)
	if !isGitRepo(wtPath) {
		return commitOutcome{Status: "error", Message: "no live worktree for this session"}
	}
	if _, err := git(wtPath, "add", "-A"); err != nil {
		return commitOutcome{Status: "error", Message: clip(gitStderr(err), 1000)}
	}
	// `diff --cached --quiet` exits 0 when nothing is staged → the tree is already clean.
	if _, err := git(wtPath, "diff", "--cached", "--quiet"); err == nil {
		return commitOutcome{Status: "nochange"}
	}
	// Inline identity + --no-verify so the commit never fails on a runner with no git user.*
	// set or a repo pre-commit hook (mirrors finalizeWorktree).
	if _, err := git(wtPath,
		"-c", "user.email=runner@orbit", "-c", "user.name=Orbit Runner",
		"commit", "--no-verify", "-m", "orbit: commit "+req.Branch); err != nil {
		return commitOutcome{Status: "error", Message: clip(gitStderr(err), 1000)}
	}
	logln(fmt.Sprintf("committed worktree changes for session %s onto %s", req.SessionID, req.Branch))
	return commitOutcome{Status: "committed"}
}

// gitStderr extracts git's stderr from a failed git() call (Output() puts it on ExitError).
func gitStderr(err error) string {
	if ee, ok := err.(*exec.ExitError); ok {
		return strings.TrimSpace(string(ee.Stderr))
	}
	if err != nil {
		return err.Error()
	}
	return ""
}

// clip truncates s to at most n runes, appending an ellipsis when it cut anything.
func clip(s string, n int) string {
	r := []rune(s)
	if len(r) <= n {
		return s
	}
	return string(r[:n]) + "…"
}

// gcWorktrees removes leftover session checkouts whose session is no longer live — a crash
// between finalize and remove, or a cancelled session never resumed. `live` is the set of
// session ids the runner is currently driving. Branches are always preserved.
func gcWorktrees(live map[string]bool) {
	root := worktreesDir()
	entries, err := os.ReadDir(root)
	if err != nil {
		return
	}
	for _, e := range entries {
		if !e.IsDir() || live[e.Name()] {
			continue
		}
		path := filepath.Join(root, e.Name())
		// Resolve the main repo via the checkout's common git dir (<repo>/.git), so we can
		// `worktree remove` it cleanly; fall back to a plain dir removal otherwise.
		if common, err := git(path, "rev-parse", "--git-common-dir"); err == nil && common != "" {
			if !filepath.IsAbs(common) {
				common = filepath.Join(path, common)
			}
			repoRoot := filepath.Dir(common)
			if _, err := git(repoRoot, "worktree", "remove", "--force", path); err == nil {
				_, _ = git(repoRoot, "update-ref", "-d", baseRefName(e.Name()))
				logln("gc: removed orphan worktree", e.Name())
				continue
			}
		}
		_ = os.RemoveAll(path)
		logln("gc: removed orphan worktree dir", e.Name())
	}
}
